<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DentalClinic.Domain\DentalClinic.Domain.csproj" />
    <ProjectReference Include="..\..\src\DentalClinic.Application\DentalClinic.Application.csproj" />
    <ProjectReference Include="..\..\src\DentalClinic.Infrastructure\DentalClinic.Infrastructure.csproj" />
  </ItemGroup>

</Project>