<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- StyleCop.Analyzers -->
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <!-- MediatR -->
    <PackageVersion Include="MediatR" Version="14.2.0" />
  </ItemGroup>
</Project>